---
  splunk:
    - username: svcSplunkUser
    - password: GLGroup987
    - earliest_time: 2012-12-04T00:00:00-0000
    - latest_time: 2012-12-04T23:59:00-0000
    - num_results: 2500
    - search_query: search host="txsearch*" source="D:\\LogFiles\\searcher\\querylog.log"
    - splunk_host: splunk-api.glgint.net
  xmlrpc:
    - url0: http://10.45.206.106:9002/xmlrpc
    - url1: http://search.glgint.net:9999/xmlrpc
